version : '3.8'
services:
  ruoyi-mysql:
    container_name: ruoyi-mysql
    image: mysql:5.7
    restart: always
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db/:/docker-entrypoint-initdb.d/
    privileged: true
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'ruoyi-media'
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - thh
  ruoyi-redis:
    container_name: ruoyi-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    privileged: true
    volumes:
      - ./redis/conf/redis.conf:/home/thh/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/thh/redis/redis.conf
    networks:
      - thh
  ruoyi-nginx:
    container_name: ruoyi-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "9000:9000"
      - "9898:9898"
      - "8600:8600"
    privileged: true
    volumes:
      - ./nginx/html/file/data:/home/thh/projects/file_data
      - ./nginx/html/admin/dist:/home/thh/projects/web-ui/vue-admin
      - ./nginx/html/web/dist:/home/thh/projects/web-ui/vue-web
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - thh
  ruoyi-admin:
    container_name: ruoyi-admin
    build:
      context: ./ruoyi/admin
      dockerfile: dockerfile
    ports:
      - "6868:6868"
    privileged: true
    volumes:
      - ./nginx/html/file/data:/home/thh/projects/file_data
    depends_on:
      - ruoyi-redis
      - ruoyi-mysql
    links:
      - ruoyi-redis
      - ruoyi-mysql
    networks:
      - thh
  ruoyi-web:
    container_name: ruoyi-web
    build:
      context: ruoyi/web
      dockerfile: dockerfile
    ports:
      - "7070:7070"
    privileged: true
    volumes:
      - ./nginx/html/file/data:/home/thh/projects/file_data
    depends_on:
      - ruoyi-redis
      - ruoyi-mysql
    links:
      - ruoyi-redis
      - ruoyi-mysql
    networks:
      - thh
networks:
  thh:
    external: true
